import { ThemeProvider } from "next-themes"
import { Inter } from "next/font/google";
import Shell from "@/components/layout/Shell";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`${inter.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Shell>{children}</Shell>
        </ThemeProvider>
      </body>
    </html>
  );
}
