import { ThemeProvider } from "next-themes"
import { Inter } from "next/font/google";
import Shell from "@/components/layout/Shell.jsx";
import ErrorBoundary from "@/components/ui/error-boundary";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
      >
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem
          disableTransitionOnChange
        >
          <ErrorBoundary>
            <Shell>{children}</Shell>
          </ErrorBoundary>
        </ThemeProvider>
      </body>
    </html>
  );
}